### ISSUE TITLE
Entering component mode when Viewport Edit mode is set to monochromatic switches the Edit Mode back to Normal mode

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#11444]
**Describe the bug**
When Viewports _Edit Mode_ is manually set to **Monochromatic** mode and then the component mode on any viable entity is entered the _Edit Mode_ switches back to **Normal** mode.

This occurs with every component that can be edited in Component Mode.

Please note that this occurs only when the EditorModeFeedback feature is enabled.
 
For more information please refer to the attached video file.
 
**Prerequisites**:
 * The selected project was built and EditorModeFeedback was enabled for it by including
```
    "Amazon": {
        "Preferences": {
            "EnableEditorModeFeedback": true,
```
lines in project's _editorpreferences.setreg_ file.

**Steps to Reproduce**:
 1. Launch the Editor and create a new level.
 2. Navigate to the Viewport top toolbar and change the _Edit Mode_ to **Monochromatic**.
 3. Create a new entity and add **White box** component to it.
 4. Enter the **White box** component mode by clicking the _Edit_ button.

**Expected behavior**
Viewport stays in the **Monochromatic** Edit Mode when the Component Mode is entered.

**Actual behavior**
Viewport switches back to the **Normal** Edit Mode when the Component Mode is entered.

**Screenshots/Video**
https://user-images.githubusercontent.com/86953456/185932450-8fe844b8-5d68-4086-842d-d633dc08a8ef.mp4

**Found in Branch**
Development (23cc830)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by hultonha** [comment]
Note: These may be related - https://github.com/o3de/o3de/issues/11186

**Comment by AMZN-daimini** [comment]
I could still reproduce this on latest stabilization. (Was gonna report it again so I'm glad I found this :D )

**Comment by hultonha** [comment]
@jonawals Could you please double check this and see if it's still not working? Should this be fixed in stabilization? Thanks!

**Comment by jonawals** [comment]
I cannot reproduce this issue locally on `a1ba826eec37b238cc236ef940d06cef3aadeb30`. It might have been fixed with `b455b1bd526ac252659266baef7d56afb8388954` (merged yesterday Wed Sep 14 19:54:20 2022 +0100).

**Comment by AMZN-daimini** [comment]
Tried again on latest stabilization, I still see this.

![LosingFocusVisualizationOnComponentEdit](https://user-images.githubusercontent.com/82231674/190488172-4bffa6e9-efb5-481a-b412-ac222c1ef740.gif)

**Comment by hultonha** [comment]
Isn't this intentional @AMZN-daimini? Do we not want to show the 'Prefab Edit Mode' visual queue when you're in Component Mode, or should it 'nest' (so if you're in Prefab Edit Mode and then start Component Mode is should stay on). Might be a good question for @rainbj.

**Comment by AMZN-daimini** [comment]
No, this is not intentional. The different "modes" should nest.

Which is also why I don't really like the fact that we call both "modes" since it can cause some confusion in this kind of discussion :)

**Comment by hultonha** [comment]
Thanks for the info @rainbj, I am pretty certain the change from @jonawals resolves this ambiguity and follows the pattern you described. Could you please confirm @jonawals? Thanks!

**Comment by jonawals** [comment]
I can confirm having manually tested on commit `b83f5351b8009b76da62aba23b96ca2ce1b5915b` (latest stab branch at time of writing) that these changes are in and behaving as described by @rainbj

**Comment by jonawals** [comment]
https://user-images.githubusercontent.com/77458631/192515601-110e9fb1-9368-4324-ac55-c2b327fcb849.mp4
