### ISSUE TITLE
Material: When bring in a new fbx to editor, the color material doesn't work anymore.

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#14067]
**Describe the bug**
When bring in a new fbx to editor, the color material doesn't work anymore. This used to work in previous o3de build.

**Assets required**
[YH_TPose.zip](https://github.com/o3de/o3de/files/10419581/YH_TPose.zip)

**Steps to reproduce**
1. Create an empty entity
2. Add actor component
3. Add the test model

**Expected behavior**
Material should show different color

**Actual behavior**
material are all white

**Screenshots/Video**
in blender:
![image](https://user-images.githubusercontent.com/69218254/212526094-9e147420-1a58-4083-b4d1-0e57fefeaa85.png)

previous build (before 12/20/2022)
![image](https://user-images.githubusercontent.com/69218254/212526111-0688f14c-b13f-46b8-94e0-ae91a320f105.png) 

recent build (1/11/2023)
![image](https://user-images.githubusercontent.com/69218254/212526164-d3a3c48e-c299-4016-a181-875d724b1471.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by BytesOfPiDev** [comment]
Can concur. I thought it was something I was doing wrong. :sweat_smile:

**Comment by AMZN-stankowi** [comment]
Is this issue fixed by this? https://github.com/o3de/o3de/pull/14036

**Comment by junbo75** [comment]
Verified that the issue is fixed by https://github.com/o3de/o3de/pull/14036.
![image](https://user-images.githubusercontent.com/68558268/212975182-2b43c293-e950-459b-a925-b5550980c7d0.png)

**Comment by amzn-rhhong** [comment]
![image](https://user-images.githubusercontent.com/69218254/213094384-1e016893-1f58-4099-ac24-ffd720f4dd6b.png)
still have this after getting latest. Is there anything else you did to make this work?
