### ISSUE TITLE
Deleting a Transform component when the "Pick an object in the viewport" mode is active crashes the Editor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#14998]
**Describe the bug**
It is possible to delete an entity's _Transform_ component when the _Pick an object in the viewport_ mode is active. This results in a crash.

Please note that the crash reproduces even if the _Pick an object in the viewport_ was initiated from another component or tool (i.e. _Entity Reference_ component or _Script Canvas_ tool). 

Please refer to the attached videos for the two ways of reproducing the issue and log files for more details.

**Call stack trace**
```
25) 00007FFCFA260207 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFCF9732486 (InProcessClient64) : (function-name not available)
23) 00007FFCF9732518 (InProcessClient64) : (function-name not available)
22) 00007FFCF97323E1 (InProcessClient64) : (function-name not available)
21) 00007FFCFC515530 (ntdll) : memset
20) 00007FFCFC4FC876 (ntdll) : _C_specific_handler
19) 00007FFCFC51241F (ntdll) : _chkstk
18) 00007FFCFC4C14A4 (ntdll) : RtlRaiseException
17) 00007FFCFC510F4E (ntdll) : KiUserExceptionDispatcher
16) D:\Git\o3de\Code\Framework\AzCore\AzCore\std\containers\vector.h (1095) : AZStd::vector<AZ::EntityId,AZStd::allocator>::insert_iter<AZStd::basic_const_iterator<AZStd::list_iterator<AZ::EntityId> > >
15) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\ViewportSelection\EditorTransformComponentSelection.cpp (321) : AzToolsFramework::EntityIdVectorFromContainer<AZStd::unordered_set<AZ::EntityId,AZStd::hash<AZ::EntityId>,AZStd::equal_to<AZ::Ent
14) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\ViewportSelection\EditorTransformComponentSelection.cpp (2602) : `AzToolsFramework::EditorTransformComponentSelection::OnActionRegistrationHook'::`7'::<lambda_2>::operator()
13) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\ActionManager\Action\EditorAction.cpp (280) : AzToolsFramework::EditorAction::Trigger
12) 00007FFCAE6A09AA (Qt5Core) : QObject::qt_static_metacall
11) 00007FFCC2E05DBF (Qt5Widgets) : QAction::activate
10) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\ActionManager\Action\ActionManager.cpp (158) : AzToolsFramework::ActionContextWidgetWatcher::TriggerActiveActionsWithShortcut
 9) D:\Git\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\ActionManager\Action\ActionManager.cpp (95) : AzToolsFramework::ActionContextWidgetWatcher::eventFilter
 8) 00007FFCAE68388C (Qt5Core) : QCoreApplicationPrivate::sendThroughObjectEventFilters
 7) 00007FFCC2E1498D (Qt5Widgets) : QApplicationPrivate::notify_helper
 6) 00007FFCC2E12510 (Qt5Widgets) : QApplication::notify
 5) 00007FFCAE6817CB (Qt5Core) : QCoreApplication::notifyInternal2
 4) 00007FFCC2E5E5EE (Qt5Widgets) : QSizePolicy::QSizePolicy
 3) 00007FFCC2E149A1 (Qt5Widgets) : QApplicationPrivate::notify_helper
 2) 00007FFCC2E13A23 (Qt5Widgets) : QApplication::notify
 1) 00007FFCAE6817CB (Qt5Core) : QCoreApplication::notifyInternal2
```

**Steps to reproduce**
1. Open any level.
2. Select any entity.
3. In the _Transform_ component click _Pick an object in the viewport_ next to the _Parent entity_ field.
4. Select the _Transform_ component.
5. Press the _Delete_ key on keyboard.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/223691724-49d7f13b-aed7-4fdc-87f1-85132ffea48b.mp4

https://user-images.githubusercontent.com/86953108/223692145-5bb0618a-6c68-48b3-a256-254a452e9591.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3f0b4de

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[error.log](https://github.com/o3de/o3de/files/10919774/error.log)
[error.zip](https://github.com/o3de/o3de/files/10919775/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/10919782/Editor.log)

**Comment by AMZN-daimini** [comment]
Fixed by the PR above.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed on build Stabilization/2305 (169ab99), this issue still occurs on build Development (73e54c6) as the PR was merged only to Stabilization branch.
