### ISSUE TITLE
Outdated Checkboxes are used in Presets Editor

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#15046]
**Describe the bug**
The outdated Checkboxes are used in the Presets Editor instead of Radio Buttons or ComboBoxes.

**Steps to reproduce**
1. Open the Material Canvas.
2. Open the Preset Editor.
3. Change the Construct Type to "Node Group".
4. Click on any checkbox.
5. Click on it again.

**Expected behavior**
The checkbox remains selected. The Radio Buttons are being used.

**Actual behavior**
Selection goes back to the General group.

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/224335019-5da10195-6a60-4410-b9ad-ce0627b179fb.mp4)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9c8d4f2

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: 22.04.2 LTS
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by gadams3** [comment]
https://github.com/o3de/o3de/pull/15010 should resolve this issue because the checkbox column cannot be selected independently of the name column

**Comment by LB-KacperMetelski** [comment]
Reopening the issue as not fixed on commit 8fbad22; checkboxes still present with the same behaviour.

**Comment by LB-KacperMetelski** [comment]
The main issue with the checkboxes was not the row selection but rather its behavior and the outdated design. In most cases, the checkbox design in O3DE is different and can be seen in the Primitive Collider component in the attached video. As for the behavior, checkboxes should be used for a multiple selection of options while the radio button for a single option. In the Preset Editor, the selection looks like a checkbox but behave like a radio button, allowing for only one option to be selected.

[Video](https://user-images.githubusercontent.com/110163473/227186268-7b357b8f-f0f0-4b49-8a85-6764c2afd4c0.mp4)

![image](https://user-images.githubusercontent.com/110163473/227186443-9b79e648-471d-4a73-990b-2a13c0298d0c.png)

**Comment by gadams3** [comment]
I see. There was a legitimate issue in the original video, where it was possible to select the check box for the preset separately from the name for the preset. This meant that the checkbox for one preset could be clicked while another one was highlighted. This was incredibly confusing and caused other issues. That's what I understood was wrong based on the original video and what I considered fixed. 

As far as the visual style of the checkbox, the preset editor is a table view with a column for a text field and another column for a check box. In this case, it is just a checkbox, consistent with other tables, and not a property as seen in the inspector. We have regular check boxes in other locations like the material component generate materials dialog and other places in UI.

Radio boxes are usually reserved for a set of options or flags affecting a single value, the same as a combo box. In this case, even though only one row can be set to default at a time, each row is an independent entry in the table, and more than one row can be selected and deleted at a time. If the window was changed to only contain a radio box with one option per preset then you would only be able to enable and disable them and not select them for deletion.

Closing this issue because it should be a table with checkboxes and because another issue was actually discovered and fixed as a result of the video.
