### ISSUE TITLE
DPE Inspector: Component cards are sometimes larger than they need to be and resize appropriately once clicked

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15945]
**Describe the bug**
Component cards are sometimes larger than they need to be and resize appropriately once clicked.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled in the AutomatedTesting project:
```
Editor.exe --ed_enableDPE=true
```
2. Open a new or existing level.
3. Create an an entity and add several components with variously sized component cards.
4. Click component cards.

**Expected behavior**
Component cards are appropriately sized as soon as they're added to an entity.

**Actual behavior**
Component cards sometimes display as larger than they need to be. Once clicked, they resize appropriately.

**Screenshots/Video**
https://github.com/o3de/o3de/assets/82226555/8af0cd37-c53f-483d-aac2-7b370ab55955

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5b31c80d4cf626bf92c9421ae6ff7797427e0253

**Additional context**
1. This appears to be due to adding specific components before adding others. Component cards appear to be sized for previously added components, and then resize once clicked to the appropriate size.

**Comment by alexmontAmazon** [comment]
need to force QWidget::update when new model is set

**Comment by LB-ArturZieba** [comment]
Issue reoccurred on Development (0eaa719) on multiple components. Please note that selecting the components does not fix the issue.

**Comment by LB-ArturZieba** [comment]
Reopening the issue as it occurs on Development (3210473).

**Comment by alexmontAmazon** [comment]
@LB-ArturZieba can we have an example of this please? Is this Linux-only now?

**Comment by LB-ArturZieba** [comment]
We have been able to reproduce this only on Linux today (Development (c9db420) build).

Attaching a video showcasing this:

https://github.com/o3de/o3de/assets/86952082/912407bd-eb8e-49b3-8892-aa1dc4dbd497

**Comment by alexmontAmazon** [comment]
fixed by https://github.com/o3de/o3de/pull/16813

**Comment by LB-ArturZieba** [comment]
Reopening the issue, as it still occurs on some components on both Windows and Linux on Development ([fa9fe53](https://github.com/o3de/o3de/commit/fa9fe5340e5cfb2be2e1eeab625c00351d7f3b26)) and Point-Release/23101 ([0d490a2](https://github.com/o3de/o3de/commit/0d490a2b4b5e04fd17edf4850c91f94361d4b836)) branches. So far it has been noticed on *Lua Script*, *Audio Environment*, and *Audio Animation* components, though please note that this list not extensive, and more components may be affected by this.

Screenshots of the affected components:
![DPEAudioAnimation](https://github.com/o3de/o3de/assets/86952082/e0bd2cf8-1af2-46de-8910-2ef2e289b180)
![DPEAudioEnvironment](https://github.com/o3de/o3de/assets/86952082/824a7f88-1a36-4734-94e4-b9ffb014119b)
![DPELuaScript](https://github.com/o3de/o3de/assets/86952082/8980b64b-c9e3-4391-8796-49b92dafea1e)
