### ISSUE TITLE
Linux: Pressing the ` key opens everything in Editor

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16189]
**Describe the bug**
If the User leaves the Game Mode and then presses the ` key, the Save Level As window opens. Closing this window results in opening everything else that can be opened.
The issue occurs on both .deb and .snap installers on any project created. On Github Development build we were able to reproduce this issue on Default template project with all gems enabled, while on the AutomatedTesting project this issue does not occur.
Please refer to the attached video for more information.

**Steps to reproduce**
1. Enter Game Mode.
2. Exit Game Mode.
3. Press the ` key.

**Expected behavior**
IMGUI opens without issues.

**Actual behavior**
Others windows opens instead of IMGUI.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86952318/eab66bc5-9c16-4eaf-96a6-660589513819

**Found in Branch**
.deb installer (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb)
.snap installer (https://o3debinaries.org/2.1.0/Linux/o3de_2.1.0_amd64.snap)
Development (ac4de00)

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by michalpelka** [comment]
I experienced issues as well.

**Comment by AMZN-alexpete** [comment]
This may have been fixed by https://github.com/o3de/o3de/pull/16254

**Comment by LB-MichalRodzos** [comment]
Issue still occurs. verified on Development build (3b9855d).  Verified on machine with Ubuntu 20.04.
