### ISSUE TITLE
DPE Inspector: Sub Priority property on certain Vegetation assets does not have upper limit on its value

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16509]
**Describe the bug**
*Sub Priority* property on *Vegetation Layer Blender*, *Vegetation Layer Blocker*, and *Vegetation Layer Blocker (Mesh)* does not have upper limit (limited [0 - 2^31]) on its value. Without DPE enabled this value is restricted [0 - 100] on the slider and [0 - 10000] overall.

**Steps to reproduce**
1. Execute the `ed_enableDPE 1` command in the *Console*.
2. Create an entity and add either *Vegetation Layer Blender*, *Vegetation Layer Blocker*, or *Vegetation Layer Blocker (Mesh)* to it.
3. In the added component, set the value of *Sub Priority* to a value outside of its expected values (for example 12345).

**Expected behavior**
*Sub Priority* property is restricted to [0 - 10000] values.

**Actual behavior**
*Sub Priority* property does not have upper limit.

**Video**

https://github.com/o3de/o3de/assets/86952082/06ea0cfa-cd26-430a-9626-75b2c6188b1f

**Found in Branch**
Development (1ed05c8)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ed05c8f21ebe203712128f1e473dc9bc7d7a4ab

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
fixed by https://github.com/o3de/o3de/pull/16471

**Comment by LB-ArturZieba** [comment]
Reopening the issue as it still occurs on Development (4b68b1f) build on Linux. It should be noted that this issue is fixed on Windows.

**Comment by cgalvan** [comment]
This been fixed on linux with this PR: https://github.com/o3de/o3de/pull/16626

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on Linux on the Stabilization/2310 (6f4ea1d)) branch.
