### ISSUE TITLE
DPE Inspector: Local Player Index value in Input component has no limits

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16529]
**Describe the bug**
With DPE Inspector disabled the Local Player Index value in Input component can be set to [-1-3]. However, with DPE Inspector enabled the value has no limits.

Please note that this issue occurs only on Linux platform.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a new entity.
2. Add an Input component to the created entity.
3. Change the Local Player Index value to different numbers.
4. Enable DPE Inspector via ed_enableDPE 1 command in the console.
5. Change the Local Player Index value again.

**Expected behavior**
Local Player Index can be set to values between [-1-3] with DPE Inspector enabled.

**Actual behavior**
Local Player Index value has no limits with DPE Inspector enabled.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86952318/b48d5cb2-2e77-47c3-88ff-bf26fe4f73f8

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d44c577

**Desktop/Device:**

- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by alexmontAmazon** [comment]
fixed, likely by https://github.com/o3de/o3de/pull/16471

**Comment by LB-ArturZieba** [comment]
Reopening the issue as it still occurs on Linux on the Development (1ea0a41) build. It does not occur on Windows.

**Comment by cgalvan** [comment]
This has been fixed on linux by PR: https://github.com/o3de/o3de/pull/16626

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed on Linux on the Stabilization/2310 (6f4ea1d)) branch.
