### ISSUE TITLE
DPE Inspector: Random Seed value in FastNoise Gradient component changes by a different number with DPE Inspector enabled and disabled

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16528]
**Describe the bug**
Changing Random Seed for FastNoise Gradient component with DPE Inspector disabled has different value steps compared to Inspector with DPE enabled. While using key arrows, mouse scroll or arrow buttons in the Entity Inspector, the Random Seed value changes by 10 when DPE Inspector is disabled. When DPE Inspector is enabled, the value changes by 1.

Please note that this issue occurs only on Linux platform.

Please refer to the attached screenshot for more information.

**Steps to reproduce**
1. Create a new entity.
2. Add a FastNoise Gradient component to the created entity.
3. Add all required components that Entity Inspector asks for.
4. Change Random Seed value without using the slider.
5. Enable DPE Inspector via `ed_enableDPE 1` command in the console.
6. Change Random Seed value again.

**Expected behavior**
Random Seed value is changed by the same number with DPE Inspector enabled and disabled.

**Actual behavior**
Random Seed value changes by a different number with DPE Inspector enabled and disabled.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86952318/35ae7711-035d-4e38-be31-55fde4b583ce

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d44c577

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by cgalvan** [comment]
This was fixed with the numeric editor attributes fixes: https://github.com/o3de/o3de/pull/16471 and https://github.com/o3de/o3de/pull/16521

**Comment by LB-KacperKapusta** [comment]
Reopening the issue as it still occurs in Development (https://github.com/o3de/o3de/commit/ec22e96a90392793025b6b961aa228e122612ff6) on Linux and the behavior remains inconsistent.

https://github.com/o3de/o3de/assets/86953659/63cbfa21-1540-4940-9754-8f566ca63642

**Comment by cgalvan** [comment]
This has been fixed on linux by PR: https://github.com/o3de/o3de/pull/16626

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2310 (6f4ea1d)) branch.
