### ISSUE TITLE
Bug Report - Monolithic Game Export created via Export Script does not work in Output folder

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#16632]
**Describe the bug**
When invoking export_source_built_project.py to export a game from O3DE, the Game Launcher that is created in build/launcher/bin/release works as expected, but the launcher inside the Game Package in the output folder will immediately stop responding upon launch. 

If the game is run via command prompt with the param "bg_ConnectToAssetProcessor=0", you will actually get an error in the logs. Here is what it says:

O3DE could not initialize correctly due to the following reason(s):
Bus const char *__cdecl AZ::EBus<class Audio::AudioSystemImplementationRequests, class Audio::AudioSystemImplementationRequests>::GetName(void) has multiple threads in its callstack records. Configure MutexType on the bus, or don't send to it from multiple threads.

After some troubleshooting it appeared that my project was lacking a Dependencies.xml file, which the Asset Bundler was throwing an error about saying it could not find it. This coud posibly have something to do with the issue, but I am unsure. Dependencies.xml files do not come native with newly created O3DE projects.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. With a project using audio, invoke the export script to export a standalone monolithic game build in release config and attempt to run it within the output folder.

**Expected behavior**

Game should launch without issues.

**Actual behavior**
A clear and concise description of what actually happened.

Game launches but remains at a white screen with

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
latest commit: commit #16605 

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Winsows 11
 - Version 22H2
 - GPU RTX 3090
 - Memory 64GB

**Additional context**

**Comment by AMZN-Gene** [comment]
Could you provide the export script used?

Here's an example for the export-project script I used.
```
 D:\prj\o3de\scripts\o3de.bat export-project -es D:\prj\o3de\scripts\o3de\ExportScripts\export_source_built_project.py --project-path D:\prj\multiplayersample\ --log-level INFO --output-path D:\MPSExport --build-tools --config release --archive-output zip --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\BasePopcornFxSeedList.seed --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\GameSeedList.seed --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\VFXSeedList.seed -assets --no-unified-launcher 
 ```

Release builds with have _bg_ConnectToAssetProcessor_ already set to 0, so opening with _bg_ConnectToAssetProcessor=0_ shouldn't be necessary. Monolithic release builds will read assets from pak files (instead of lose files found inside of your cache folder). The export script will package all the necessary files based on the dependencies found inside of the seedlist provided to the export script.
Is your sound bnk file inside of your seedlists? (no other assets reference the bnk, so O3D won't know to automatically pull it into the package)

**Comment by TheOneAbis** [comment]
Here is the script I used:

.\o3de.bat export-project -es C:\O3DE\o3de\scripts\o3de\ExportScripts\export_source_built_project.py --project-path C:\O3DE\stateofmatter-o3de\StateOfMatter\ --log-level INFO --output-path C:\O3DE\stateofmatter-o3de\output --build-tools --config release --archive-output zip --seedlist C:\O3DE\stateofmatter-o3de\StateOfMatter\AssetBundling\SeedLists\SOMSeedList.seed -assets --no-unified-launcher --no-server-launcher

SOMSeedList contains Main.bnk, so sound should be good.

**Comment by AMZN-Gene** [comment]
I think Wwise generates an “init.bnk” too. Might check that as well…

**Comment by TheOneAbis** [comment]
i included both init and main.bnk, i dont think im coming across audio errors anymore, but now i am getting build dependency problems as shown below:

![image](https://github.com/o3de/o3de/assets/26350896/138b7d31-0a32-4dac-baf6-4d7aebe31f9a)

the list of errors goes on for quite a while, this is just a small snippet of it.

**Comment by AMZN-Gene** [comment]
> i included both init and main.bnk, i dont think im coming across audio errors anymore, but now i am getting build dependency problems as shown below:
> 
> ![image](https://user-images.githubusercontent.com/26350896/265089180-138b7d31-0a32-4dac-baf6-4d7aebe31f9a.png)
> 
> the list of errors goes on for quite a while, this is just a small snippet of it.

Glad the audio errors have been fixed. I do notice that sometimes Atom changes require deleting the entire cache folder. The errors says it can find the builder for PBR materials, which is just standard rendering. Could you delete the cache folder and rerun the exporter? 
Also, probably a good uses to create a new git hub issue for these new errors so the Atom can see it.

**Comment by TheOneAbis** [comment]
I deleted the cache folder and re-ran the export script, im no longer seeing all these errors thankfully, but theres still no difference.Launcher still will not run, and the Game.log only has this to say:

```
<16:45:26> BackupNameAttachment=" Build(0) 05 Sep 23 (16 45 26)"  -- used by backup system
<16:45:26> Log Started at Tue Sep  5 16:45:26 2023
<16:45:26> Built on Sep  5 2023 13:09:42
<16:45:26> Running 64 bit Windows version
<16:45:26> FileVersion: 0.0.0.0
<16:45:26> ProductVersion: 0.0.0.0
<16:45:26> Using Microsoft (tm) C++ Standard Library implementation
<16:45:26> Project Path: C:\O3DE\stateofmatter-o3de\output\StateOfMatterGamePackage

<16:45:26> Project Name: StateOfMatter

<16:45:26> > cl_assetLoadWarningEnable : true

<16:45:26> > cl_assetLoadWarningMsThreshold : 100

<16:45:26> Loading Config file game.cfg (C:/O3DE/stateofmatter-o3de/output/StateOfMatterGamePackage/Cache/pc/game.cfg)
<16:45:26> creating CVarGroups from directory 'Config/CVarGroups' ...
<16:45:26> [Warning] Config file user.cfg not found!
<16:45:26> GameName: StateOfMatter
<16:45:26> BuildTime: Sep  5 2023 13:09:42
<16:45:26> > g_languageAudio : en-US

<16:45:26> AudioEngineWwise created!
```

**Comment by TheOneAbis** [comment]
hello, any updates on the above? any ideas what could be wrong here? considering where the log stops, im thinking there is still some sort of isue with Wwise, but not sure what it could be

**Comment by AMZN-Gene** [comment]
The logs aren’t displaying any error. What happens when opening the game launcher? Does it crash? Does it still crash if you don’t attempt to load any level?

**Comment by TheOneAbis** [comment]
Upon opening the launcher it stays at a white screen then says not responding. Yes, i am calling loqdlevel from a setreg, it probably just never makes it there.

**Comment by TheOneAbis** [comment]
hello, sorry this took so long. I put this on the backburner while I focus on other things. I tried a build again, this time without a setreg file so there should not be any levels loading. I also went into the seedlist and removed everything but init.bnk and main.bnk, so there really shouldnt be anything related to the game being built. However, the launcher still will not run.

**Comment by AMZN-Gene** [comment]
Regarding the dependencies.xml this might be related https://github.com/o3de/o3de/issues/15338

**Comment by AMZN-Gene** [comment]
>stays at a white screen then says not responding
Darn, that sounds like a crash on startup, which I have not seen.

Was it always showing a white screen and then "not responding" or did that only happen when you removed the level from the seedlist?

I'd leave in level in the seedlist, and maybe also create a super simple level just to test the starting level. Also start the first level via C++ instead of setreg (I'm not sure how setreg behave in release mode and C++ will rule out any setreg issues)

**Comment by TheOneAbis** [comment]
Showing a white screen has always been happpening.

Could you show me how to set the startup level in c++? Not sure how to do this

**Comment by AMZN-Gene** [comment]
```
auto loadLevelCommand = AZStd::string::format("LoadLevel %s", "levels/your_level/your_level.spawnable");
AZ::Interface<AZ::IConsole>::Get()->PerformCommand(loadLevelCommand.c_str());
```

**Comment by TheOneAbis** [comment]
Ah cool, where should I put this command?

**Comment by AMZN-Gene** [comment]
In your game's systemcomponent's Activate()

**Comment by TheOneAbis** [comment]
I built again with the console command in c++ and it is set to load one of our small testing scenes, still no luck.

**Comment by TheOneAbis** [comment]
hey, should this issue be closed? since it's been fixed a while ago, though idk if the root cause of it (which I think you said was and issue with the compression gem) was actually fixed, since we simply just omitted the gem entirely from our project in order to get exports working
