### ISSUE TITLE
Multiple Calls to DrawTextOnScreen Overlap Each Other

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2578]
**Describe the bug**
When you call DrawTextOnScreen in a Script Canvas multiple times, it appears the system is attempting to treat each node as a separate line, but the spacing is not enough.

**To Reproduce**
1. Create a script like the one shown below.
2. Add a Script Canvas component to any object in the scene
3. Ctrl-G to enter Game Mode
4. Notice that "Line 1", "Line 2", and "Line 3" are overlapping.

![image](https://user-images.githubusercontent.com/55155825/127404326-4f0b24de-2385-414e-82d4-24f0d9886593.png)
![image](https://user-images.githubusercontent.com/55155825/127404348-2b7715b7-0029-45f3-8583-d09e6cf3d2c3.png)

**Expected behavior**
The lines should not be overlapping, as if there was a newline ('\n') between each.
![image](https://user-images.githubusercontent.com/55155825/127404425-a6823d3d-6060-4f0a-8f12-f2410cf4736c.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
Dual 4k monitors with 150% desktop scaling.

**Comment by lsemp3d** [comment]
Assigning to sig/graphics-audio, the debug draw API exposure is a rendering feature exposed to scripting

**Comment by wintermute-motherbrain** [comment]
Believe this is fixed.  @santorac to verify.

**Comment by santorac** [comment]
I confirmed this still occurs as of:
commit 9edbe4d541ccc998601514897984f39afa899271 (HEAD -> development)
