### ISSUE TITLE
Go to selected object action performed repeatedly on the same object stutters the camera movement

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3926]
**Describe the bug**
It has been noticed that performing the "Go to selected object" action repeatedly in the Viewport on the same entity causes the current camera movement interpolation to restart back at zero, effectively stuttering/halting the movement.

**To Reproduce**
1. Select an entity in the Viewport (e.g. Shader Ball child entity of the Atom Default Environment) and move your camera away from the entity.
2. Press Z (Shortcut for the "Go to selected object" action) repeatedly.

**Expected behavior**
The camera movement interpolation is not reset each time the Z key is pressed.

**Video**

https://user-images.githubusercontent.com/86952082/131991857-b8981cbc-e46a-402f-8a18-47ee5ead55b1.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment]
This is closely related to this bug - https://github.com/o3de/o3de/issues/4141. I can fix in combination with some other small camera improvements.

**Comment by hultonha** [comment]
Fixed by #5703

**Comment by LB-ArturSiewniak** [comment]
Issue verified as fixed on Stabilization_2110 (d30fdb7) build, but still occurs on Development (e804fd2) - should this issue be reopened?

**Comment by hultonha** [comment]
No it's just that stabilization won't have been merged to development yet, so it should be fixed in dev soon 👍 Thanks!
