### ISSUE TITLE
Editor crashes after changing the layout when the Prefab system is enabled

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4364]
**Describe the bug**
Editor crashes after restoring the default layout, changing it to a previously saved one, or reloading the current layout. The issue only occurs when the Prefab system is enabled and a level is loaded.

**To Reproduce**
1. Create a level.
2. Navigate to View > Layouts and select Restore Default Layout.

**Expected behavior**
The layout is loaded successfully.

**Screenshots**

https://user-images.githubusercontent.com/86952009/135061597-3bf50992-812c-415d-8855-d8744154e515.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7242773/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7242774/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7242775/dump.zip)

**Comment by LB-BartoszDudzinski** [comment]
Verified as fixed in development

**Comment by LB-ArturSiewniak** [comment]
This issue still occurs on build Development (3791149) with Prefabs System both enabled and disabled. It does not occur on build Stabilization_2110 (7031147) with Prefabs System either enabled or disabled. Reopening the issue.

**Comment by AMZN-daimini** [comment]
Hey @LB-ArturSiewniak,
While the repro steps and the end result (a crash) is the same, the causes of it may be different. For this kind of situation, would it be possible to open a new issue that references the previous one, instead of re-opening ones that are already closed? 

For example, since this new repro is in development only, it should go through triage again and it likely will not be prioritized as blocker. Re-opening a blocker makes it much harder to track what's going on.

If you could just create a new issue with your comment and link to this one for reference, that would be extremely helpful :D Thanks!

**Comment by LB-ArturSiewniak** [comment]
Hi! The issue was separately reported here: https://github.com/o3de/o3de/issues/5699.
