### ISSUE TITLE
Bug Report: Access violation error occurs with EditorLib.dll 

### ISSUE THREAD

**Issue by il-Salvatore** [o3de/o3de#4598]
**Describe the bug**
Access violation error occurs with EditorLib.dll - > referencing vector.h, line 489:         
AZ_FORCE_INLINE const_iterator          end() const         { return const_iterator(AZSTD_POINTER_ITERATOR_PARAMS(m_last)); }

VS2019 reports it as such: Unhandled exception thrown: read access violation.
this was 0x18.

**To Reproduce**
Start up O3DE project manager (o3de.exe)
Go to any project and click on "open editor" on any project including the automated testing project. 

With VS2019 debugger attached it will show the issue clearly. 

Note: If done without VS the editor silently crashes to desktop leaving the asset processor and asset builder still running but idle.

**Expected behavior**
Editor should open with the project loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/91893235/136762103-9ae7129e-cf78-4145-8f6a-0adfaf6c5109.png)

Screenshot of VS2019 in debug mode, showing the exception notification

**Desktop/Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10
 - Version Win10x64,  build 17134.rs4_release.180410-1804
 - CPU Intel Core I5-2500k, unlocked
 - GPU nVidia Geforce GTX 1050 TI OC 4GB GDDR5
 - Memory 20GB DDR3

PS. this issue still occurs on my windows 10 install after upgrading it to build v.1904

**Comment by wintermute-motherbrain** [comment]
This issue was likely fixed by this PR: https://github.com/o3de/o3de/pull/5151

**Comment by wintermute-motherbrain** [comment]
@il-Salvatore after grabbing the PR above can you verify if this is still happening?  Thanks!

**Comment by il-Salvatore** [comment]
When I try to go into the automated testing project I am still getting read access violation, from line 2171 in file CryEdit.cpp. 

The error message about the maestro gem not being enabled for the project still comes up, even if I manually enable it.

Entire output of such a debug run included below:

'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Editor.exe'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\ntdll.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Program Files (x86)\AVG\Antivirus\aswhook.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\kernel32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\KernelBase.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\ws2_32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\rpcrt4.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\crypt32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Qt5Core.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\ucrtbase.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\user32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\win32u.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\gdi32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\gdi32full.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msvcp_win.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\advapi32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msvcrt.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\ole32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\sechost.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\combase.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\bcrypt.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\mpr.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\shell32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\userenv.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\version.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\netapi32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\vcruntime140.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\vcruntime140_1.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\winmm.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msvcp140.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msvcp140_1.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\netutils.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\srvcli.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\cryptbase.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\imm32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\SHCore.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\EditorLib.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\EditorCommon.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\AzQtComponents.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\EditorCore.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Qt5Svg.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Qt5Widgets.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Qt5Gui.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1151_none_91a40286cc884949\GdiPlus.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Qt5Xml.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\Magnification.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\uxtheme.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\dwmapi.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\d3d11.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\dxgi.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\wtsapi32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\d3d9.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\windows.storage.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\kernel.appcore.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\wldp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\bcryptprimitives.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\platforms\qwindows.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\oleaut32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\shlwapi.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\profapi.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\powrprof.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\umpdc.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msasn1.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\cryptnet.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\wintrust.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\imagehlp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\cryptsp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\rsaenh.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\opengl32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\glu32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\msctf.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\clbcatq.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\AppXDeploymentClient.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9be48e12ebceea24\nvoglv64.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\setupapi.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\cfgmgr32.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\drvstore.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\devobj.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\ntmarta.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\DXCore.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\winsta.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\styles\qwindowsvistastyle.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qico.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qgif.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qicns.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qjpeg.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qsvg.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qtga.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qtiff.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qwbmp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\imageformats\qwebp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_DX12.Builders.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_DX12.Private.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\D3D12.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_Metal.Builders.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_Metal.Private.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_Vulkan.Builders.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI_Vulkan.Private.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_Feature_Common.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\ImGui.imguilib.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RHI.Private.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Atom_RPI.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\AtomLyIntegration_CommonFeatures.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\LmbrCentral.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\GradientSignal.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Camera.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\Maestro.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\PrefabBuilder.Builders.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\SceneData.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\SceneCore.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\SceneProcessing.Editor.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\SceneBuilder.dll'. Symbols loaded.
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\assimp-vc142-mt.dll'. Module was built without symbols.
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\mswsock.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\XInput9_1_0.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\sspicli.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\TextInputFramework.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\CoreUIComponents.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\CoreMessaging.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\WinTypes.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\TextShaping.dll'. 
The thread 0x3af8 has exited with code 0 (0x0).
ProcessWatcher: GetExitCodeProcess failed (6), assuming process either failed to launch or terminated unexpectedly
Process Watcher: ProcessWatcher::LaunchProcessAndRetrieveOutput: Unable to launch process ' p4 set'
Source Control: Perforce Warning - Command has failed 'set'
Source Control: 
==================================================================
Source Control: Trace::Warning
 G:/o3de/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.cpp(1035): 'void __cdecl AzToolsFramework::PerforceComponent::VerifyP4PortIsSet(void)'
Source Control: Perforce - P4PORT (server address) is not set, Perforce not available!

Source Control: ==================================================================
Source Control: Perforce configuration invalid
Qt: QCommandLineParser: option not defined: "dummyString"
Qt: QCommandLineParser: option not defined: "dummyString"
Qt: Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9be48e12ebceea24\nvldumdx.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9be48e12ebceea24\nvd3dumx.dll'. 
The thread 0x1ba4 has exited with code 0 (0x0).
'Editor.exe' (Win32): Unloaded 'G:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9be48e12ebceea24\nvd3dumx.dll'
'Editor.exe' (Win32): Unloaded 'G:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9be48e12ebceea24\nvldumdx.dll'
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\DataExchange.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\dcomp.dll'. 
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\twinapi.appcore.dll'. 
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\iconengines\qsvgicon.dll'. 
AssetSystemComponent: Failed to read branch token from bootstrap. Calculating Branch Token: 0xC9FFBEB3
Asset System Connection: Asset Processor Connection IP: 127.0.0.1, port: 45643, branch token 0xC9FFBEB3
The thread 0x2b7c has exited with code 0 (0x0).
AssetProcessorConnection::ConnectThread: 
==================================================================
AssetProcessorConnection::ConnectThread: Trace::Warning
 G:/o3de/o3de/Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp(231): 'void __cdecl AzFramework::AssetSystem::AssetProcessorConnection::ConnectThread(void)'
AssetProcessorConnection::ConnectThread: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection::ConnectThread: ==================================================================
The thread 0x124c has exited with code 0 (0x0).
The thread 0xfac has exited with code 0 (0x0).
The thread 0xc3c has exited with code 0 (0x0).
AssetSystem: Ping time to asset processor: 0.33 milliseconds
The thread 0x4b10 has exited with code 0 (0x0).
AssetCatalog: Registering asset "fonts/vera.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "presets/mobilesettings/gpuanddriverlists.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-extrabold.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/splitbundletest/splitbundle.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "platform/android/android_project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/platform/ios/atomshadercapabilities.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/vera_releasenotes.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "license_apache2.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/vera_copyright.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/platform/mac/atomshadercapabilities.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "license_mit.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "platform/ios/ios_project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "platform/linux/linux_project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/splitbundletest/splitbundle__1.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/default_aws_resource_mappings.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "shaders/lightculling/license for amd bitonic sort code.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "platform/windows/windows_project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/bundle/staticdata.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "shaders/diffuseglobalillumination/nvidia rtx-gi license.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "lightingpresets/lowcontrast/readme.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/shader_global_build_options.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/veramono.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "presets/mobilesettings/mobilefeatureblacklist.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/bundle/nocatalog.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/bundle/gamepropertiessmall_pc.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/testmaterials.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-bolditalic.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "license.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/license.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "styles/assetprocessorglobalstylesheetvariables.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "platform/mac/mac_project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "resources/platform/ios/images.xcassets/testdpappicon.appiconset/contents.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/bundle/gamepropertiesuserrequest_pc.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "resources/platform/ios/images.xcassets/launchimage.launchimage/contents.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-semibolditalic.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "resources/platform/mac/images.xcassets/contents.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "resources/platform/mac/images.xcassets/testdpappicon.appiconset/contents.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "code/gem.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "envhdri/photo_studio_01.lightingconfig.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/nvidia.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/intel.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "lightingpresets/readme.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-light.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-lightitalic.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "imgui.ini" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "project.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/config.dat" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-semibold.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "materials/presets/macbeth/readme.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/platform/android/atomshadercapabilities.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "test/bundle/ping.pak" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-extrabolditalic.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-regular.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "materials/presets/pbr/metal.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-italic.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "resources/platform/ios/images.xcassets/contents.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "aztest_bootstrap.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "fonts/open_sans/opensans-bold.ttf" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "pytest.ini" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "slicebuildersettings.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/amd.txt" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "engine.json" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "system_mac_mac.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "uicanvaseditorresolutionpresets.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/ios_medium.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/pc_low.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "system_ios_ios.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/pc_veryhigh.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "editor.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "modellingpanel.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/android_gpus.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "leveltemplates.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/vid_capture_setup.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "game.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "scripts/ai/navigation.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/vr.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "system_linux_pc.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "objecttemplates.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/cvargroups/sys_spec_full.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "ui/assetbrowserribbon.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "libs/materialeffects/surfacetypes.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/android_high_nogmem.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "autoexec.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/vid_capture_reset.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/artprof_user.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/aidebug.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "materials/shaderlist.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "system_windows_pc.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/android_low.cfg" via AssetSystem message, but type is not set.
The thread 0x1b38 has exited with code 0 (0x0).
The thread 0x4aa0 has exited with code 0 (0x0).
The thread 0x237c has exited with code 0 (0x0).
AssetCatalog: Registering asset "config/spec/android_medium.cfg" via AssetSystem message, but type is not set.
The thread 0x588 has exited with code 0 (0x0).
AssetCatalog: Registering asset "editorparticlepanelsdefault.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/benchmark_gpu.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "plugins/particleeditorplugin/settings/tooltips.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/autotestchain.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/autotestplaythrough.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/multiplayer_console.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/android_models.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "default_time_of_day.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/statoscope.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/vid_capture_stop.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/rigidbodyex.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/ios_low.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "ui/wipfeatures.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "libs/posteffectgroups/default.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/android_veryhigh.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/android_high.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/livingentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/recording.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/multiplayer.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/comment.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/pc_high.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/user.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/autotesttimedemo.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areabox.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "plugins/particleeditorplugin/defaults/defaultparticleemitters.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/vid_capture_start.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/livingentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/livingentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/livingentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/livingentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "libs/materialeffects/fxlibs/collisions.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "propertyenumerations.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/particleeffect.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/gpu/ios_models.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/uicanvasref.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/multiplayer_pc.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "editorparticlepanels.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "toolbox.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "system_android_android.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/ios_veryhigh.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/singleplayer.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "crydesigner_timeofday.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/hdd_cache.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/perfhud_pc.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/android_malit760.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/audioarearandom.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/mgpu.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/pc_medium.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "soundtemplates.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/spec/ios_high.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/rigidbody.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "usertools.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/benchmark_cpu.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areatrigger.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/light.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "mapscreenshotsettings.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "config/artprof.cfg" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/uicanvasref.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/uicanvasref.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/uicanvasref.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/uicanvasref.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/smartobject.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/camerasource.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "engine_dependencies.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/proceduralobject.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/proximitytrigger.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/fogvolume.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/basicentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "libs/materialeffects/materialeffects.xml" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areasphere.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/audioareaambience.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/cactorwrapper.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/tagpoint.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/audioareaentity.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areashape.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/audiotriggerspot.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/environmentlight.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/navigationseedpoint.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areasolid.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/animobject.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/cameratarget.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/geomcache.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "entities/areabeziervolume.ent" via AssetSystem message, but type is not set.
AssetCatalog: Registering asset "translation/scriptcanvas_en_us.qm" via AssetSystem message, but type is not set.
The thread 0x3ec8 has exited with code 0 (0x0).
The thread 0x3f4 has exited with code 0 (0x0).
The thread 0x3b00 has exited with code 0 (0x0).
The thread 0x6d8 has exited with code 0 (0x0).
AssetSystem: Ping time to asset processor: 1.28 milliseconds
'Editor.exe' (Win32): Loaded 'G:\o3de\o3de\build\bin\profile\CrySystem.dll'. Symbols loaded.
BackupNameAttachment=" Build(0) 09 Nov 21 (20 35 13)"  -- used by backup system
Log Started at Tue Nov  9 20:35:13 2021
Built on Nov  9 2021 18:20:35
Running 64 bit Windows version
FileVersion: 0.0.0.0
ProductVersion: 0.0.0.0
Using Microsoft (tm) C++ Standard Library implementation
<20:35:13> Loading Config file system_windows_pc.cfg (G:/Users/Iain/.o3de/Projects/NewProject/Cache/pc/system_windows_pc.cfg)
System: Loading system configuration from system_windows_pc.cfg...<20:35:13> Loading system configuration from system_windows_pc.cfg...
System: Project Path: G:\Users\Iain\.o3de\Projects\NewProject
<20:35:13> Project Path: G:\Users\Iain\.o3de\Projects\NewProject
System: Project Name: NewProject
<20:35:13> Project Name: NewProject
Logger: > cl_assetLoadWarningEnable : true
<20:35:13> (Logger) - > cl_assetLoadWarningEnable : true
Logger: > cl_assetLoadWarningMsThreshold : 100
<20:35:13> (Logger) - > cl_assetLoadWarningMsThreshold : 100
<20:35:13> Loading Config file game.cfg (G:/Users/Iain/.o3de/Projects/NewProject/Cache/pc/game.cfg)
<20:35:13> creating CVarGroups from directory 'Config/CVarGroups' ...
<20:35:13> Loading Config file system_windows_pc.cfg (G:/Users/Iain/.o3de/Projects/NewProject/Cache/pc/system_windows_pc.cfg)
<20:35:13> Loading Config file user.cfg (G:/Users/Iain/.o3de/Projects/NewProject/Cache/pc/config/user.cfg)
<20:35:13> GameName: NewProject
<20:35:13> BuildTime: Nov  9 2021 18:20:35
<20:35:13> [Warning] (System) - <Audio>: Running without any AudioSystem!
System: Time initialization<20:35:13> Time initialization
System: Initializing additional systems<20:35:13> Initializing additional systems
<20:35:13> [CVARS]: [DUPLICATE] CXConsole::RegisterString(const char*): variable [sys_PakWarnOnPakAccessFailures] is already registered
<20:35:13> [CVARS]: [DUPLICATE] CXConsole::RegisterString(const char*): variable [t_Scale] is already registered
<20:35:13> [CVARS]: [DUPLICATE] CXConsole::RegisterString(const char*): variable [sys_PakMessageInvalidFileAccess] is already registered
<20:35:13> [CVARS]: [DUPLICATE] CXConsole::RegisterString(const char*): variable [sys_report_files_not_found_in_paks] is already registered
System: 
==================================================================
<20:35:14> ==================================================================
System: Trace::Assert
 G:/o3de/o3de/Code/Legacy/CrySystem/SystemInit.cpp(1204): (16132) 'bool __cdecl CSystem::Init(const struct SSystemInitParams &)'
<20:35:14> Trace::Assert
 G:/o3de/o3de/Code/Legacy/CrySystem/SystemInit.cpp(1204): (16132) 'bool __cdecl CSystem::Init(const struct SSystemInitParams &)'
System: Error initializing the Cinematic System. Please check that the Maestro Gem is enabled for this project.
<20:35:14> Error initializing the Cinematic System. Please check that the Maestro Gem is enabled for this project.
System: ------------------------------------------------
<20:35:14> ------------------------------------------------
'Editor.exe' (Win32): Loaded 'G:\Windows\System32\dbghelp.dll'. 
System: G:\o3de\o3de\Code\Legacy\CrySystem\SystemInit.cpp (1205) : CSystem::Init
<20:35:14> G:\o3de\o3de\Code\Legacy\CrySystem\SystemInit.cpp (1205) : CSystem::Init
System: G:\o3de\o3de\Code\Legacy\CrySystem\DllMain.cpp (100) : CreateSystemInterface
<20:35:14> G:\o3de\o3de\Code\Legacy\CrySystem\DllMain.cpp (100) : CreateSystemInterface
System: G:\o3de\o3de\Code\Editor\GameEngine.cpp (403) : CGameEngine::Init
<20:35:14> G:\o3de\o3de\Code\Editor\GameEngine.cpp (403) : CGameEngine::Init
System: G:\o3de\o3de\Code\Editor\CryEdit.cpp (1051) : CCryEditApp::InitGameSystem
<20:35:14> G:\o3de\o3de\Code\Editor\CryEdit.cpp (1051) : CCryEditApp::InitGameSystem
System: G:\o3de\o3de\Code\Editor\CryEdit.cpp (1684) : CCryEditApp::InitInstance
<20:35:14> G:\o3de\o3de\Code\Editor\CryEdit.cpp (1684) : CCryEditApp::InitInstance
System: G:\o3de\o3de\Code\Editor\CryEdit.cpp (4195) : CryEditMain
<20:35:14> G:\o3de\o3de\Code\Editor\CryEdit.cpp (4195) : CryEditMain
System: G:\o3de\o3de\Code\Editor\main.cpp (32) : main
<20:35:14> G:\o3de\o3de\Code\Editor\main.cpp (32) : main
System: C:\qt_build\Lumberyard3rdPartyQt\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
<20:35:14> C:\qt_build\Lumberyard3rdPartyQt\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
System: d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
<20:35:14> d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
System: 00007FFC9E9E7034 (KERNEL32) : BaseThreadInitThunk
<20:35:14> 00007FFC9E9E7034 (KERNEL32) : BaseThreadInitThunk
System: 00007FFC9FDA2651 (ntdll) : RtlUserThreadStart
<20:35:14> 00007FFC9FDA2651 (ntdll) : RtlUserThreadStart
System: ==================================================================
<20:35:14> ==================================================================
System: 
==================================================================
<20:35:14> ==================================================================
System: O3DE could not initialize correctly for the following reason(s):
Error initializing the Cinematic System. Please check that the Maestro Gem is enabled for this project.<20:35:14> O3DE could not initialize correctly for the following reason(s):
Error initializing the Cinematic System. Please check that the Maestro Gem is enabled for this project.
System: 
==================================================================
<20:35:14> ==================================================================
<20:37:43> System Shutdown
Editor: 
==================================================================
Editor: Trace::Error
 G:\o3de\o3de\Code\Editor\CryEdit.cpp(4197): 'int __cdecl CryEditMain(int,char *[])'
Editor: O3DE Editor did not initialize correctly, and will close.
This could be because of incorrectly configured components, or missing required gems.
See other errors for more details.
Editor: ==================================================================
Exit: Called ExitInstance() with exit code: 0x1Exception thrown: read access violation.
**gEnv** was nullptr.

The program '[15788] Editor.exe' has exited with code 0 (0x0).

**Comment by AMZN-alexpete** [comment]
@il-Salvatore the logs you posted indicate the Editor was trying to use your NewProject and not AutomatedTesting.  Are you launching the editor from the Project Manager or are you clicking editor.exe in your NewProject folder?

This is one way you could launch the AutomatedTesting project from Project Manager (assuming it has been built)
![image](https://user-images.githubusercontent.com/26804013/141030143-a7fe194c-5d08-4183-9ee6-d8cd6114a94a.png)

To verify the Maestro gem is enabled you should see a line for Maestro in the [AutomatedTesting/Gem/Code/enabled_gems.cmake file](https://github.com/o3de/o3de/blob/stabilization/2110/AutomatedTesting/Gem/Code/enabled_gems.cmake#L46)

**Comment by il-Salvatore** [comment]
I can confirm the above is true, my O3DE install points to g:\o3de\o3de in both places mentioned,  and in the config for the automated testing project the maestro gem is listed as enabled. 

Everything did work correctly after I did a full rebuild of said project.

Just a quick question regarding building the project from an end-user perspective: would it not be helpful for the project manager to inform users their project must be built when they create it before they can start working on it? 

My experience is that the project manager only mentions this once the gem config has been changed.

Regarding further technical difficulties of the aforementioned type after doing said build, I have experienced none further and no access violations from editorlib.dll

**Comment by AMZN-alexpete** [comment]
Thanks for confirming @il-Salvatore and I'm glad to hear the full re-build fixed the issue. 

In your original repro steps for this issue - did you not build the projects first before pressing the `Open Editor` button?

> Start up O3DE project manager (o3de.exe)
> Go to any project and click on "open editor" on any project including the automated testing project.

The current Project Manager does require and suggest user's build newly created projects, however, there are known situations where the Project Manager does not detect that a project needs to be built.  For example, if you were to close the Project Manager before building the project and then re-open it, the prompt to build the project may not be visible.  We have a task to improve this detection in future releases.

Also, if you feel that this issue is resolved or is not an issue anymore please close the issue.

**Comment by il-Salvatore** [comment]
Thanks for the response.

I believe this resolves the issue I was experiencing, in part because of not knowing then to first do a build before opening the editor, from experience with other engines that don't follow the same build before edit procedure. 

Closing this issue.
