### ISSUE TITLE
Cursor movement is replaced by camera rotation after specific interaction with entity in Viewport

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#5748]
**Describe the bug**
When clicking on the entity’s gizmo or arrows and holding it with the left mouse button while clicking the right mouse button, the cursor disappears and mouse movement is switched to camera rotation. Input can be changed back by clicking the right mouse button and moving the mouse while it is pressed.
 Please refer to the attached video for more information.
 
**Steps to reproduce**
1. Create an entity.
2. Press and hold the left mouse button when cursor is on entity’s gizmo.
3. Press the right mouse button while holding left mouse button and move the mouse.
4. Release the left mouse button.
5. Notice that the cursor disappears, and camera rotation is the default behavior of mouse movement.

**Expected behavior**
When the right mouse button is held during other interaction with an entity, the mouse movement is translated into the camera rotation until the right mouse button is released.

**Actual behavior**
When the right mouse button is pressed while entity’s gizmo is held with the left mouse button, the camera rotation becomes the default behavior of the mouse movement.

**Video**

https://user-images.githubusercontent.com/86953282/142438314-009487b4-58be-45eb-8309-a64e2df49ef3.mp4

**Found in Branch**
Stabilization_2110 (d222aee)

**Desktop/Device:**
 • Device: PC
 • OS: Windows
 • Version: 10 Pro
 • CPU: Intel i7 8700k
• GPU: Nvidia RTX 2080
 • Memory: 16GB

**Comment by hultonha** [comment]
Hi @LB-KacperSzczepanski,

Thanks for reporting this, I ran into something similar recently (https://github.com/o3de/o3de/issues/6388) which is fixed by this PR (https://github.com/o3de/o3de/pull/6425). I can repro the issue you're describing but I don't fully understand what the expected behavior is. Would you expect the manipulator to keep moving while LMB and RMB are held? I can see a worse issue if you press and hold LMB (on a Manipulator) then press and hold RMB and move the mouse, and then release RMB. The cursor disappears and you have to press and hold RMB and the move the mouse and then release to have it appear again.

I should be able to fix that but I just want to make sure I understand exactly what you think should happen (I think there are a few 'correct' behaviors and we might have to just pick the simplest for now).

**Comment by LB-KacperSzczepanski** [comment]
Hi @hultonha
I would expect the behavior to be similar to that in other tools. In some cases nothing happens when RMB is clicked while LMB is held. In most tools in this situation Context Menu is opened.

**Comment by hultonha** [comment]
Thanks for the info @LB-KacperSzczepanski. In O3DE the context menu will not display until RMB up, so showing it won't help with this issue. Perhaps simply having RMB do nothing while LMB is pressed is the best solution and will give the least unexpected behavior, does that fit with your expectation? Thanks!

**Comment by LB-KacperSzczepanski** [comment]
@hultonha It sounds like a good solution. Thank you.,

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/pull/15454

**Comment by LB-MateuszPlatakis** [comment]
Issue verified as fixed on Stabilization/2305 (a6ca494) branch. On Development (987119e) branch the issue is still active.
