### ISSUE TITLE
Linux: Resizing the Editor window causes a (Swapchain) message spam in the Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7319]
**Describe the bug**
Resizing the Editor window causes the following message to be printed to Console multiple times:
```
(Swapchain) - Swapchain created. Width: <number>, Height: <number>
(Swapchain) - Obtained presentable images.
(Swapchain) - Acquired the first image.
```

**Steps to reproduce**
1. Resize the Editor window.

**Expected behavior**
There are no (Swapchain) messages printed to Console.

**Actual behavior**
(Swapchain) messages are spammed to Console.

**Video**

https://user-images.githubusercontent.com/86952082/151968515-f28dbc96-28c2-4b58-b655-bb1bef71e533.mp4

**Found in Branch**
Development (f5fcab7)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by superkitcath** [comment]
@LB-ArturZieba, could you try this again with the latest version? This may have been fixed. I will leave the issue open until you confirm, thanks!

**Comment by LB-ArturZieba** [comment]
@superkitcath The issue still occurs on the Development (61f1dc1) build, confirmed on three different PCs.
