### ISSUE TITLE
Atom_TestSuite_Main intermittently hangs

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7486]
**Describe the bug**
Locally executing Atom_TestSuite_Main results in unexpected intermittent failures. This appears to be due to a hang, with multiple minutes passing between the final log message and the test termination. These failures may be occurring in Automated Review, though logs are not available to prove this. Local testing showed a failure in 12/100 executions, with two locations emitting a similar failure pattern.

11 failures ocurred in:
```
E   Failed: Test AtomLevelLoadTest_Editor:
E   Test TIMED OUT after 300 seconds
```
1 failure was in:
```
E   Failed: Test ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges:
E   Test TIMED OUT after 300 seconds
```

Note that the log snippets above are a high-level failure reason, and not the true root cause. Inspecting the logs suggests there is a hang occurring, but the cause of the hang is unknown.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -R AutomatedTesting::Atom_TestSuite_Main --output-on-failure --repeat until-fail:100`
4. See intermittent error

**Expected behavior**
Test execution consistently succeeds

**Actual behavior**
Test intermittently fails, due to what appears to be a hang

**Found in Branch**
Development @ https://github.com/o3de/o3de/commit/4982787043a45449ef37a1435e37402611918ceb

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia
 - Memory 32GB

**Additional context**
Logs are attached below:
[AtomMain.txt](https://github.com/o3de/o3de/files/8025825/AtomMain.txt)
[AtomMain2.txt](https://github.com/o3de/o3de/files/8025826/AtomMain2.txt)
[AtomMain3.txt](https://github.com/o3de/o3de/files/8025827/AtomMain3.txt)
[AtomMain4.txt](https://github.com/o3de/o3de/files/8025828/AtomMain4.txt)

**Comment by jromnoa** [comment]
Should be fixed in https://github.com/o3de/o3de/pull/7513

**Comment by Kadino** [comment]
#7513 disables the test, but notably does not fix the underlying issue. Recommend keeping at least one issue open to track the underlying crash.

**Comment by jromnoa** [comment]
We have new tickets cut internally to resolve this. Will post PRs and update once the work is complete. It has been de-prioritized until our next batch of work since the pipeline is no longer blocked since we sandboxed it.

**Comment by jromnoa** [comment]
These tests have been massively improved and fixed since this ticket was cut. For instance, the `ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges` test runs on the periodic suite now for monitoring this crash. Additionally, the level tests are now in their own file and launch as their own set of tests so that they don't collide with other types of tests (such as `ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges`): https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py 

You can check all of our test launcher modules here: https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/PythonTests/Atom/T
