### ISSUE TITLE
Physics entities with assigned physics materials do not retain them when their Prefab is spawned via Script Canvas

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7550]
**Describe the bug**
If a Prefab of a physics entity with a custom physics material assigned is spawned, it does not retain its properties. It should be noted that the same Prefab placed manually in the level keeps its physics material properties.

**Steps to reproduce**
1. Go to Tools > PhysX Configuration (PREVIEW).
2. In the Physics Materials section click the "Edit asset" button to the far right of the "Physics Material Library" property.
3. In the .physmaterial opened in the Asset Browser click the + (Add new child element) in the top right.
4. Change the created child element's properties: set the Restitution to 1.0, and Restitution combine to "Maximum" and save the .physmaterial asset.
5. Create a platform entity (PhysX Shape Collider, Box Shape - make sure the Game View property is enabled, and the X and Y dimensions are set to 5).
6. Create a Rigid Body entity (PhysX Shape Collider, Sphere Shape - make sure the Game View property is enabled, PhysX Rigid Body).
7. In the Rigid Body entity's PhysX Shape Collider component set the Physics Materials > Entire object property to the material saved in step 4.
8. Place the Rigid Body entity above the platform entity and enter the Game Mode to verify that it continually bounces.
9. Right-click the Rigid Body entity, select the "Create Prefab..." from the dropdown menu and save the prefab.
10. Create a Spawn entity (With only the Script Canvas component) above the platform entity next to the Rigid Body entity.
11. In the Script Canvas recreate the script shown below under the **Assets required** section (Spawn Script Canvas).
12. Attach the created Script Canvas graph to the entity created in step 10.
13. Enter the Game Mode.

**Expected behavior**
Both physics Prefabs show the same behavior.

**Actual behavior**
Spawned Prefab does retain the physics material properties of the original Prefab.

**Assets required**
Spawn Script Canvas
![SpawnScriptCanvas](https://user-images.githubusercontent.com/86952082/153427001-7317b027-31c4-4e6c-9932-3a196eb61a62.PNG)

**Video**

https://user-images.githubusercontent.com/86952082/153427022-3bbdef0c-82dc-4f45-a374-7613edd1cc42.mp4

**Found in Branch**
Development (1c3a619)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-MateuszSzweda** [comment]
Tagging @hultonha  as per request on PhysX issues that stand out in during exploratory testing and user workflow scenarios.

**Comment by moraaar** [comment]
I was able to reproduce this in stabilization branch. I will investigate what's happening.

**Comment by moraaar** [comment]
Issue fixed in stabilization by https://github.com/o3de/o3de/pull/8924

NOTE: The prefab asset might need to be deleted from cache folder before being reprocessed by Asset Processor.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on Development (e106142) build, still occurs on Stabilization_2205 (201271c).

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization_2205 (651a5a3) build.
