### ISSUE TITLE
Editor crashes after entering Game Mode during Simulate mode with an asset assigned to a Blast Family component

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#8714]
**Describe the bug**
Entering the Game Mode during Simulate mode with an asset assigned to the Blast Family component causes the Editor to crash. The issue occurs only on Windows as Nvidia Blast is not available on other platforms. Please refer to the attached logs for more information.

**Steps to reproduce**
1. Open the Editor and create a new level.
2. Create an Entity.
3. Add the Blast Family component.
4. Assigned any Blast Asset.
5. Enter Simulate mode (Ctrl +P).
6. Enter Game Mode (Ctrl + G).

**Expected behavior**
The user is able to enter Game Mode at any time.

**Actual behavior**
Editor crashes after entering Game Mode during Simulate mode with an asset assigned to the Blast Family component.

**Call Stack Trace:**
```
14) 00007FF954A1B857 (KERNELBASE) : UnhandledExceptionFilter
13) 00007FF9572951B0 (ntdll) : memset
12) 00007FF95727C766 (ntdll) : _C_specific_handler
11) 00007FF9572920CF (ntdll) : _chkstk
10) 00007FF957241454 (ntdll) : RtlRaiseException
 9) 00007FF957290BFE (ntdll) : KiUserExceptionDispatcher
 8) C:\o3de\o3de\Gems\Blast\Code\Source\Components\BlastFamilyComponent.cpp (510) : Blast::BlastFamilyComponent::ApplyStressDamage
 7) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Jobs\Internal\JobManagerBase.cpp (31) : AZ::Internal::JobManagerBase::Process
 6) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Jobs\Internal\JobManagerWorkStealing.cpp (421) : AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal
 5) C:\o3de\o3de\Code\Framework\AzCore\AzCore\std\parallel\thread.h (193) : AZStd::Internal::thread_info_impl<`AZStd::thread::thread<`AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads'::`4'::<lambda_1> >'::`2'::<lambda_1> >::execute
 4) C:\o3de\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
 3) 00007FF954F91BB2 (ucrtbase) : configthreadlocale
 2) 00007FF955C87034 (KERNEL32) : BaseThreadInitThunk
 1) 00007FF957242651 (ntdll) : RtlUserThreadStart
```

**Video**

https://user-images.githubusercontent.com/96232062/161749861-a11aa7a7-1224-4612-9fea-ccc11c84e795.mp4

**Found in Branch**
Stabilization/2205 (https://github.com/o3de/o3de/commit/3e47df2e0fea9f57d207e6c739938bd1c4019c98)
Development (https://github.com/o3de/o3de/commit/d4f993ebf4c33285f23a5e74d55552c86efe8bcf)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Error.zip](https://github.com/o3de/o3de/files/8417892/Error.zip)
[Editor.log](https://github.com/o3de/o3de/files/8417893/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8417895/error.log)

**Comment by moraaar** [comment]
Fixed merged to stabilization/2205 branch

**Comment by LB-HubertUberman** [comment]
Reopening the issue as it still occurs on the Development branch (https://github.com/o3de/o3de/commit/6291e9d30623e83e42903aba7601952792815320). Verified as fixed on Stabilization/2205 branch (https://github.com/o3de/o3de/commit/d25f305783de49ca1edb52ef1cc8875e20772b80).

**Comment by hultonha** [comment]
Hi @LB-HubertUberman,

We have an internal process where bugs fixed in `stabilization/2205` are merged back to `development` twice a week (Tuesdays and Thursdays). Please wait to verify in development until this has happened (e.g. If a fix went in on Tuesday afternoon or Wednesday, please wait until late Thursday, or it might be even better to wait until Friday to verify in development). Feel free to leave a question on the issue if you're not sure if the merge has happened yet).

In future can you please not reopen issues in cases like this as it will make tracking the fixes harder for developers,

I'm closing this issue again and the merge from `stabilization/2205` to development should happen tomorrow.

Thanks for your understanding,


Tom

**Comment by LB-HubertUberman** [comment]
Hello @hultonha,
Thank you for clarification. We apologize for any inconvenience and we will make sure this does not happen again.

**Comment by hultonha** [comment]
No worries at all @LB-HubertUberman, I apologize this wasn't communicated clearly before, thanks for your understanding! Cheers 🙂

**Comment by LB-HubertUberman** [comment]
Issue verified as fixed on the Development (https://github.com/o3de/o3de/commit/146b2c84cfc0fc0daea2d416f91d80cec5f62bb6).
