### ISSUE TITLE
Feature Request: Motion component adding other components and default properties are unclear

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#8908]
**Is your feature request related to a problem? Please describe.**
1. When user draft and drop the fbx with simple motion on it, the property window auto added a bunch of components (multiple mesh components, and actor component), and those components weren't activated by default, and the assets field were empty. 2. User had to manually remove some of the components, and manually assign the mesh assets to the components as well. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
WF3 WTE Issue # 2

**Comment by shawstar** [comment]
When dragging and Asset Browser FBX into the scene or Dragging an FBX into the Entity Outliner you will get Many Components in the Entity Inspector. You will need to Delete unwanted Components and even reload a mesh asset on the Component you would like. Suggestion would be to Ask which FBX node relevant you would like to add as an Entity. 
![image](https://user-images.githubusercontent.com/87207603/163414935-b156ba86-61c7-4d2c-8c4d-a08213f18492.png)

**Comment by yuyihsu** [comment]
Related to https://github.com/o3de/o3de/issues/9885

The solution provided in https://github.com/o3de/o3de/issues/9885 should solve this issue.

**Comment by yuyihsu** [comment]
@monroegm can you help verify (or ask QA to verify) if https://github.com/o3de/o3de/issues/9885 will fix this issue? If yes, we can close this one with 9885 when it's closed.

**Comment by lmbr-pip** [comment]
Retested on Stabilization-2210 -  7c4e3ca268 and still occurring. 

@hultonha Has SIG/simulation looked at this at all?

**Comment by hultonha** [comment]
Hmm I see quite a lot of discussion on this ticket (https://github.com/o3de/o3de/issues/9885) from @lawsonamzn . Perhaps he has more information on this. I do not believe sig-simulation (character specifically) have looked into this as the other investigation and fix was ongoing (see this PR - https://github.com/o3de/o3de/pull/10949).

**Comment by lmbr-pip** [comment]
This actually looks like a procedural prefab issue and "as designed". These nodes are in the source scene file and we do not currently ignore empty transforms.

We would need UX help and input from others to improve this experience as theres not a clear path forward without adding more control/options to the experience esp for character import.

Proposing moving this to prefabs, and SIG/content and moving out of scope for WtE.

**Comment by hultonha** [comment]
Thanks for the info @lmbr-pip, I agree with you these seems outside the scope of sig-simulation and would be better investigated by sig-content (proc-prefabs/asset browser behavior). We're happy to be involved and support but I don't think from what I can tell this is related to code sig-simulation is responsible for.

**Comment by AMZN-stankowi** [comment]
Can you attach the scene file with the issue to this ticket? I can't repro this with the steps given.

I don't think this is related to procedural prefabs. Procedural prefabs don't include motions or actors, and the drag and drop event generating an actor component says to me this is unrelated to procedural prefabs.

**Comment by nick-l-o3de** [comment]
This appears fixed with latest dev - if I drop an actor with a motion in (the fbx), it drops just the actor in.
If I drop the FBX file itself, same thing
If I open the fbx and drop the mesh, I get just the mesh component.
If I open the FBX and drop the actor, I get just the actor.
I know the actor has a motion since I can assign it to it and it plays in the viewport.
