### ISSUE TITLE
Lua editor disconnects first try after opening scriptcanvas first

### ISSUE THREAD

**Issue by GraphiteSIX** [o3de/o3de#9779]
**Describe the bug**

Lua editor disconnects first try after opening scriptcanvas first

**Steps to reproduce**
1. Add scriptcanvas component and load script
2. Open IDE and choose editor for target
3. See error

**Expected behavior**
Editor connects to debugger
**Actual behavior**
Various disconnection messages

**Assets required**
[Untitled-1.zip](https://github.com/o3de/o3de/files/8778340/Untitled-1.zip)

**Screenshots/Video**

https://user-images.githubusercontent.com/105223355/170469775-0b761062-b337-4c9a-b057-2acb1e56cedc.mp4

**Found in Branch**
Development https://github.com/o3de/o3de/commit/146b2c84cfc0fc0daea2d416f91d80cec5f62bb6

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [Microsoft Windows 11 Pro Version 10.0.22000 Build 22000]
 - CPU [AMD Ryzen 7 3800X ]
 - GPU [Radeon RX 580]
 - Memory [32GB]

**Additional context**
As i stopped recording the editor hung but didn't crash but there was a pop up behind editor window
![assprostop](https://user-images.githubusercontent.com/105223355/170469987-5ec7f728-bcc8-4b7b-9fd6-77d8c78e7001.png)

**Comment by GraphiteSIX** [comment]
Sorry about the flaky repro info I was in the middle of capturing another issue.
I repro'd again and recorded from a fresh level.
Not the usual workflow to bring in all 3 editors but it achieves the first result.

Log ------------------
<11:53:21> Successfully opened document D:/Game_Dev/PROJECTS/Foxbat/Levels/Moon/Moon.prefab
<11:53:21> Level loading time: 0.03 seconds
<11:53:21> -----------------------------------------------------------
<11:53:22> [Warning] (Model) - ray intersection against a model that is still creating spatial information
<11:53:58> (System) - Adding new socket 19816
<11:54:07> (TargetManagementComponent) - Set Target - 118708864
<11:54:07> (LUA) - Rejecting msg 0x88a2ee04 (Host is not the attached debugger)
<11:54:07> (LUA) - Received EnumContexts request
<11:54:10> [Error] (System) - Failed to read from socket (10054:An existing connection was forcibly closed by the remote host.)
<11:54:10> (System) - Removing socket 19816 due to Unknown
--------------------------
In the first video I had deleted Ui editor so maybe something is hanging from that.
Here is the second repro attempt.

https://user-images.githubusercontent.com/105223355/170475675-24704c44-00f8-4a83-bfa8-a7f7b1aeedb4.mp4

The same pop up is there behind the window but I didn't record it.

**Comment by monroegm** [comment]
Rerouting to SIG-Network for a quick check to see if the is a networking issue

**Comment by lmbr-pip** [comment]
I believe this is the same issue as https://github.com/o3de/o3de/issues/9612 and has been fixed.

**Comment by GraphiteSIX** [comment]
Just checked on https://github.com/o3de/o3de/commit/a53a366d571ec8982c151af1215cb7d07991d67a and the issue is still there unfortuntely

**Comment by GraphiteSIX** [comment]
Still getting [Error] (System) - Failed to read from socket (10054:An existing connection was forcibly closed by the remote host.)
With the exact same behavior on  https://github.com/o3de/o3de/commit/f1479668cb59b7721c36168b526290e493f42917
Can anyone else repro ?

**Comment by robhaco** [comment]
@lmbr-pip I can confirm this still reproduces in current development.  Saw the same log entries as the Graphite:
<15:24:18> (System) - Adding new socket 8224
<15:24:33> (TargetManagementComponent) - Set Target - 118708864
<15:24:33> (LUA) - Rejecting msg 0x88a2ee04 (Host is not the attached debugger)
<15:24:33> (LUA) - Received EnumContexts request
<15:24:36> [Error] (System) - Failed to read from socket (10054:An existing connection was forcibly closed by the remote host.)
<15:24:36> (System) - Removing socket 8224 due to Unknown

**Comment by GraphiteSIX** [comment]
@robhaco The AP still disconnects for me after you shut the error popup behind the editor window and wait 30 secs.
Tested on commit https://github.com/o3de/o3de/commit/917aba465b2390a5a52fc8413e0ffd86a7db7e1d
Have you tested on a later commit maybe ?

https://user-images.githubusercontent.com/105223355/171953648-8aa3459b-33f2-451f-8a53-01deb801371c.mp4

**Comment by robhaco** [comment]
@GraphiteSIX Interesting, you're actually at a slightly newer commit than what I was testing at.  I get the dialog, but no AP shutdown after closing it.  I'll pull newer just to be safe.  Thanks for the update.

**Comment by robhaco** [comment]
@lmbr-pip after further testing, this issue seems to be variable.  Out of 5 attempts at latest, had the asset processor shut down for 2 of the attempts.  Interestingly, during one of the attempts, none of the above issues happened and everything continued to run after connecting the LuaIDE to the Editor.  It's likely there are other factors that are making it more common for different devices.

**Comment by GraphiteSIX** [comment]
I Looked into my firewall and found loads of old AP & LuaIDE rules (Like 50+ lol), so I reset to default but made no difference I can still repro the issue.
What is strange is if I add Lua script first then scriptcanvas then ui editor it doesn't shutdown.
And If I open script canvas first then ui then LuaIDE it doesn't shutdown.
So only in the order of add UI and open, add Scriptcanvas and open, add Luascript and open and connect to editor does it disconnect and crash.
I suppose it could depend also on the window state that is saved last time you use the editor.
I managed to create a dump of LuaIDE

PROCESS_NAME:  LuaIDE.exe

ERROR_CODE: (NTSTATUS) 0xc0000374 - A heap has been corrupted.

EXCEPTION_CODE_STR:  c0000374

EXCEPTION_PARAMETER1:  00007ffbdd057780

ADDITIONAL_DEBUG_TEXT:  Enable Pageheap/AutoVerifer ; Followup set based on attribute [Is_ChosenCrashFollowupThread] from Frame:[0] on thread:[PSEUDO_THREAD]

FAULTING_THREAD:  00000be0

STACK_TEXT:  
00000000`00000000 00000000`00000000 heap_corruption!LuaIDE.exe+0x0

Unfortuntely the dump is too big for github but I have put it on my drive but if that is not ok I'm sure you can reproduce the crash and get a dump.
https://drive.google.com/file/d/1UwXklJQnapfTHvHjCriJ9TYj2SabFarD/view?usp=sharing

**Comment by GraphiteSIX** [comment]
@lmbr-pip Here is the minidump Not sure if your get enough info from it or not.
[LuaIDECrash.zip](https://github.com/o3de/o3de/files/8839072/LuaIDECrash.zip)

**Comment by lmbr-pip** [comment]
Should restest post merging of the force ticking of the LuaIDE.

Seems that this may require more work in target manager.

**Comment by GraphiteSIX** [comment]
@lmbr-pip tested on commit https://github.com/o3de/o3de/commit/046995140f0b1d44f3f4bc30ec1e11018245b711
The issue is still there unfortunately.

**Comment by LafLaurine** [comment]
Tested on development branch, can't seem to reproduce. I think issue was fixed.

**Comment by guillaume-haerinck** [comment]
Closing per comment above, issue hasn't moved for a long time while lua ide is used constantly
